DROP DATABASE IF EXISTS coders_db;
CREATE DATABASE coders_DB;

USE coders_DB;

CREATE TABLE coders(
  id INT AUTO_INCREMENT NOT NULL,
  coders_name VARCHAR(100) NOT NULL,
  devoured BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id)
);