DROP DATABASE IF EXISTS coders_db;
CREATE DATABASE coders_DB;

USE coders_DB;

CREATE TABLE coders(
  id INT NOT NULL AUTO_INCREMENT,
  coders_name VARCHAR(100) NOT NULL,
  devoured BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (id)
);